# Generated by Django 3.1.1 on 2020-12-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, height_field='452', upload_to='static/images', width_field='100'),
            preserve_default=False,
        ),
    ]
